services:
  - type: web
    name: kanchivaram-cafe-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=server/prisma/schema.prisma
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
